window.BB = Backbone;

BB.globs = {};
BB.SERVICES = {};
BB.EVENTS = {};
BB.LOADING = {};
BB.CONSTS = {};
BB.EVENTS = {};

// services
BB.SERVICES.DIGG_VIEW = 'DIGG_VIEW';
BB.SERVICES.LOADING_VIEW = 'LOADING_VIEW';

// events
BB.EVENTS.APP_STACK_VIEW = 'APP_STACK_VIEW';
